// templates/WebUIToolkit.Templates/content/vue/Frontend/src/App.vue
<template>
  <div class="container py-5">
    <div class="card border-0 shadow">
      <div class="card-body p-5">
        <span class="badge text-bg-success mb-3">Vue + CsWebUi</span>
        <h1 class="display-5">WebUIToolkitStarter</h1>
        <p class="lead mb-0">
          Edit <code>Frontend/src/App.vue</code> and save to exercise Vite HMR
          inside the native window.
        </p>
      </div>
    </div>
  </div>
</template>

// templates/WebUIToolkit.Templates/content/svelte/Frontend/src/App.svelte
<div class="container py-5">
  <div class="card border-0 shadow">
    <div class="card-body p-5">
      <span class="badge text-bg-danger mb-3">Svelte + CsWebUi</span>
      <h1 class="display-5">WebUIToolkitStarter</h1>
      <p class="lead mb-0">
        Edit <code>Frontend/src/App.svelte</code> and save to exercise Vite HMR
        inside the native window.
      </p>
    </div>
  </div>
</div>
