// templates/WebUIToolkit.Templates/content/react/Frontend/src/main.tsx
import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

function App() {
  return (
    <div className="container py-5">
      <div className="card border-0 shadow">
        <div className="card-body p-5">
          <span className="badge text-bg-primary mb-3">React + CsWebUi</span>
          <h1 className="display-5">WebUIToolkitStarter</h1>
          <p className="lead mb-0">
            Edit <code>Frontend/src/main.tsx</code> and save to exercise Vite HMR
            inside the native window.
          </p>
        </div>
      </div>
    </div>
  );
}

createRoot(document.querySelector("#app")!).render(
  <StrictMode><App /></StrictMode>,
);

// templates/WebUIToolkit.Templates/content/angular/Frontend/src/main.ts
import { Component, provideZonelessChangeDetection } from "@angular/core";
import { bootstrapApplication } from "@angular/platform-browser";

@Component({
  selector: "webuitoolkit-root",
  standalone: true,
  template: `
    <div class="container py-5">
      <div class="card border-0 shadow">
        <div class="card-body p-5">
          <span class="badge text-bg-danger mb-3">Angular + CsWebUi</span>
          <h1 class="display-5">WebUIToolkitStarter</h1>
          <p class="lead mb-0">
            Edit <code>Frontend/src/main.ts</code> and save to exercise the
            Angular development builder inside the native app workflow.
          </p>
        </div>
      </div>
    </div>
  `,
})
class App {}

await bootstrapApplication(App, {
  providers: [provideZonelessChangeDetection()],
});
